[api_keys]
govcloud = "abcdefghijklmnopqrstuvwxyz1234567890"
commercial = "abcdefghijklmnopqrstuvwxyz1234567890"

[output]
cloud_id = "cluster:abcdefghijklmnopqrstuvwxyz1234567890"
user = "elastic"
pw = "hunter32"
index = "cloud-consumption"

[[customer]]
org_id = 1234567890
system = "govcloud"
lookback = 1

[[customer.purchase]]
ecu = 2000000
date = 2024-01-01

[[customer.purchase]]
ecu = 1000000
date = 2024-02-15

[[customer.overage]]
ecu = 250012.12
date = 2024-05-01
